from typing import Optional
from datetime import datetime
from sqlmodel import Field, SQLModel

class AgentConfig(SQLModel, table=True):
    """Stores key-value configuration settings for the agent."""
    key: str = Field(primary_key=True)
    value: str
    description: Optional[str] = None
    updated_at: datetime = Field(default_factory=datetime.utcnow)

class KnowledgeChunk(SQLModel, table=True):
    """Stores chunks of knowledge from documents or URLs."""
    id: Optional[int] = Field(default=None, primary_key=True)
    content: str
    source: str
    embedding_id: Optional[str] = None  # ID in the Vector DB (Chroma)
    created_at: datetime = Field(default_factory=datetime.utcnow)

class ActionLog(SQLModel, table=True):
    """Logs actions taken by the agent (tweets, replies, likes)."""
    id: Optional[int] = Field(default=None, primary_key=True)
    action_type: str  # 'tweet', 'reply', 'like', 'follow'
    content: Optional[str] = None
    target_id: Optional[str] = None  # Tweet ID or User ID
    status: str = Field(default="pending")  # pending, approved, executed, failed
    result_json: Optional[str] = None  # JSON string of API response
    strategy_log_id: Optional[int] = Field(default=None, foreign_key="strategylog.id")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    executed_at: Optional[datetime] = None

class StrategyLog(SQLModel, table=True):
    """Logs the strategy reasoning generated by the AI."""
    id: Optional[int] = Field(default=None, primary_key=True)
    context_summary: str
    strategy_text: str
    model_name: str
    created_at: datetime = Field(default_factory=datetime.utcnow)

class AgentPersona(SQLModel, table=True):
    """Stores the persona and sales strategy settings for the agent."""
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str = Field(default="Phronel")
    role: str = Field(default="SNS Sales Representative of a leading AI Software Company")
    tone: str = Field(default="Professional, helpful, slightly witty. Use emoji sparingly.")
    constraints: str = Field(default="Max 280 chars. Direct and engaging.")
    sales_strategy: str = Field(default="Focus on providing value and solving pain points.")
    is_active: bool = Field(default=True)
